
* Emacs configuration
All the sections below will contain declarations for my emacs
setup. When using .org configuration file, please include a short line
in your .emacs or init.el file

#+HEADER: :eval no :export code
#+BEGIN_SRC :eval no
;; Include something like this your initalization file:
  (org-babel-load-file (expand-file-name "~/.emacs.d/config/config.org"))
#+END_SRC

That is to include your fresh config file! Also, be careful when
making changes. Sometimes, when making changes to settings graphically
via ~M-x customize~, emacs will create some new lines to .emacs file
and there will be duplicates with the .org config file - watch out
those! These customizations are possible to move separate ~custom.el~
file.

Well, your ~.emacs~ or ~init.el~ file and the ~config.org~ might look
something like the contents in following sections.

#+ATTR_HTML: :class important
#+BEGIN_QUOTE
[!IMPORTANT]
*IMPORTANT:* There are few things that are not configured properly,
 like tabbing works differently in different modes etc. If you wish to
 have consistent setup, please check and set keybindings.
#+END_QUOTE

* Emacs configuration
This configuration uses ~init.el~ file, and separate tangling ~config.org~ file.

** Init.el
#+begin_src emacs-lisp :tangle nil
;;; package --- Summary
;;; Commentary:
;; The rest of the configuration is taken care in a separate file, at
;; the moment called config.org but may be named whatever sensible.

;;; Code:
(add-to-list 'load-path "~/.emacs.d/config/")

;; Check if the .org file has been updated
(when (file-newer-than-file-p "~/.emacs.d/config/config.org" "~/.emacs.d/config/config.el")
  (org-babel-load-file (expand-file-name "~/.emacs.d/config/config.org")))

(org-babel-load-file (expand-file-name "~/.emacs.d/config/config.el"))

(setq custom-file "~/.emacs.d/custom.el")
(load custom-file)

(provide 'init)
;;; init.el ends here
#+end_src

** Config.org
#+INCLUDE: "./config.org"
